<a href="https://colab.research.google.com/github/AhmesM78/EmployeeManagementSystem/blob/main/NLP_T2_Data_Acquisition.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install pandas snscrape google-play-scraper youtube-comment-downloader playwright

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Collecting snscrape
  Downloading snscrape-0.7.0.20230622-py3-none-any.whl.metadata (4.9 kB)
Collecting google-play-scraper
  Downloading google_play_scraper-1.2.7-py3-none-any.whl.metadata (50 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 50.2/50.2 kB 1.3 MB/s eta 0:00:00
Collecting youtube-comment-downloader
  Downloading youtube_comment_downloader-0.1.78-py3-none-any.whl.metadata (2.9 kB)
Collecting playwright
  Downloading playwright-1.58.0-py3-none-manylinux1_x86_64.whl.metadata (3.5 kB)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.3)
Requirement already satisfied: requests[socks] in /usr/local/lib/python3.12/dist-packages (from snscrape) (2.32.4)
Requirement already satisfied: lxml in /usr/local/lib/python3.12/dist-packages (from snscrape) (6.0.2)
Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python3.12/dist-packages (from snscrape) (4.13.5)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from snscrape) (3.25.2)
Collecting dateparser (from youtube-comment-downloader)
  Downloading dateparser-1.4.0-py3-none-any.whl.metadata (31 kB)
Collecting pyee<14,>=13 (from playwright)
  Downloading pyee-13.0.1-py3-none-any.whl.metadata (3.0 kB)
Requirement already satisfied: greenlet<4.0.0,>=3.1.1 in /usr/local/lib/python3.12/dist-packages (from playwright) (3.3.2)
Requirement already satisfied: typing-extensions in /usr/local/lib/python3.12/dist-packages (from pyee<14,>=13->playwright) (4.15.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4->snscrape) (2.8.3)
Requirement already satisfied: regex>=2024.9.11 in /usr/local/lib/python3.12/dist-packages (from dateparser->youtube-comment-downloader) (2025.11.3)
Requirement already satisfied: tzlocal>=0.2 in /usr/local/lib/python3.12/dist-packages (from dateparser->youtube-comment-downloader) (5.3.1)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests[socks]->snscrape) (3.4.6)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests[socks]->snscrape) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests[socks]->snscrape) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests[socks]->snscrape) (2026.2.25)
Requirement already satisfied: PySocks!=1.5.7,>=1.5.6 in /usr/local/lib/python3.12/dist-packages (from requests[socks]->snscrape) (1.7.1)
Downloading snscrape-0.7.0.20230622-py3-none-any.whl (74 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 74.8/74.8 kB 3.5 MB/s eta 0:00:00
Downloading google_play_scraper-1.2.7-py3-none-any.whl (28 kB)
Downloading youtube_comment_downloader-0.1.78-py3-none-any.whl (8.3 kB)
Downloading playwright-1.58.0-py3-none-manylinux1_x86_64.whl (46.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 46.2/46.2 MB 14.5 MB/s eta 0:00:00
Downloading pyee-13.0.1-py3-none-any.whl (15 kB)
Downloading dateparser-1.4.0-py3-none-any.whl (300 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 300.4/300.4 kB 15.5 MB/s eta 0:00:00
Installing collected packages: pyee, google-play-scraper, playwright, dateparser, youtube-comment-downloader, snscrape
Successfully installed dateparser-1.4.0 google-play-scraper-1.2.7 playwright-1.58.0 pyee-13.0.1 snscrape-0.7.0.20230622 youtube-comment-downloader-0.1.78

In [ ]:
!pip uninstall snscrape -y
!pip install git+https://github.com/JustAnotherArchivist/snscrape.git

Found existing installation: snscrape 0.7.0.20230622
Uninstalling snscrape-0.7.0.20230622:
  Successfully uninstalled snscrape-0.7.0.20230622
Collecting git+https://github.com/JustAnotherArchivist/snscrape.git
  Cloning https://github.com/JustAnotherArchivist/snscrape.git to /tmp/pip-req-build-ifgj793y
  Running command git clone --filter=blob:none --quiet https://github.com/JustAnotherArchivist/snscrape.git /tmp/pip-req-build-ifgj793y
  Resolved https://github.com/JustAnotherArchivist/snscrape.git to commit 614d4c2029a62d348ca56598f87c425966aaec66
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: requests[socks] in /usr/local/lib/python3.12/dist-packages (from snscrape==0.7.0.20230622) (2.32.4)
Requirement already satisfied: lxml in /usr/local/lib/python3.12/dist-packages (from snscrape==0.7.0.20230622) (6.0.2)
Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python3.12/dist-packages (from snscrape==0.7.0.20230622) (4.13.5)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from snscrape==0.7.0.20230622) (3.25.2)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4->snscrape==0.7.0.20230622) (2.8.3)
Requirement already satisfied: typing-extensions>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4->snscrape==0.7.0.20230622) (4.15.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests[socks]->snscrape==0.7.0.20230622) (3.4.6)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests[socks]->snscrape==0.7.0.20230622) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests[socks]->snscrape==0.7.0.20230622) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests[socks]->snscrape==0.7.0.20230622) (2026.2.25)
Requirement already satisfied: PySocks!=1.5.7,>=1.5.6 in /usr/local/lib/python3.12/dist-packages (from requests[socks]->snscrape==0.7.0.20230622) (1.7.1)
Building wheels for collected packages: snscrape
  Building wheel for snscrape (pyproject.toml) ... done
  Created wheel for snscrape: filename=snscrape-0.7.0.20230622-py3-none-any.whl size=74851 sha256=ac36bedeb160cb7e9cda2ffaef95384fb7c5015283feeee201064c222d3b8fb6
  Stored in directory: /tmp/pip-ephem-wheel-cache-up_5x2u6/wheels/23/96/eb/f46ee85f779c8e28c7981ded4e8572bfa2bbe2c5bf20ecb4f4
Successfully built snscrape
Installing collected packages: snscrape
Successfully installed snscrape-0.7.0.20230622

In [ ]:
!playwright install

Downloading Chrome for Testing 145.0.7632.6 (playwright chromium v1208) from https://cdn.playwright.dev/chrome-for-testing-public/145.0.7632.6/linux64/chrome-linux64.zip
(node:7237) [DEP0169] DeprecationWarning: `url.parse()` behavior is not standardized and prone to errors that have security implications. Use the WHATWG URL API instead. CVEs are not issued for `url.parse()` vulnerabilities.
(Use `node --trace-deprecation ...` to show where the warning was created)
167.3 MiB [] 0% 0.0s167.3 MiB [] 0% 64.6s167.3 MiB [] 0% 37.0s167.3 MiB [] 0% 26.1s167.3 MiB [] 0% 22.4s167.3 MiB [] 0% 20.8s167.3 MiB [] 0% 12.5s167.3 MiB [] 1% 8.1s167.3 MiB [] 2% 6.5s167.3 MiB [] 2% 5.6s167.3 MiB [] 3% 4.7s167.3 MiB [] 3% 5.0s167.3 MiB [] 4% 4.9s167.3 MiB [] 4% 4.6s167.3 MiB [] 5% 4.3s167.3 MiB [] 6% 4.2s167.3 MiB [] 6% 4.1s167.3 MiB [] 6% 4.0s167.3 MiB [] 7% 4.0s167.3 MiB [] 7% 3.9s167.3 MiB [] 8% 3.8s167.3 MiB [] 8% 3.7s167.3 MiB [] 9% 3.6s167.3 MiB [] 10% 3.5s167.3 MiB [] 10% 3.3s167.3 MiB [] 11% 3.2s167.3 MiB [] 12% 3.2s167.3 MiB [] 13% 3.1s167.3 MiB [] 13% 3.0s167.3 MiB [] 14% 2.9s167.3 MiB [] 15% 2.9s167.3 MiB [] 16% 2.8s167.3 MiB [] 17% 2.8s167.3 MiB [] 17% 2.7s167.3 MiB [] 18% 2.7s167.3 MiB [] 19% 2.6s167.3 MiB [] 20% 2.5s167.3 MiB [] 21% 2.5s167.3 MiB [] 22% 2.5s167.3 MiB [] 23% 2.4s167.3 MiB [] 24% 2.3s167.3 MiB [] 25% 2.2s167.3 MiB [] 26% 2.2s167.3 MiB [] 27% 2.1s167.3 MiB [] 28% 2.1s167.3 MiB [] 29% 2.0s167.3 MiB [] 30% 2.0s167.3 MiB [] 31% 1.9s167.3 MiB [] 32% 1.9s167.3 MiB [] 33% 1.8s167.3 MiB [] 34% 1.8s167.3 MiB [] 35% 1.8s167.3 MiB [] 36% 1.7s167.3 MiB [] 37% 1.7s167.3 MiB [] 38% 1.6s167.3 MiB [] 39% 1.6s167.3 MiB [] 40% 1.6s167.3 MiB [] 41% 1.5s167.3 MiB [] 42% 1.5s167.3 MiB [] 43% 1.5s167.3 MiB [] 44% 1.4s167.3 MiB [] 45% 1.4s167.3 MiB [] 46% 1.4s167.3 MiB [] 47% 1.4s167.3 MiB [] 48% 1.4s167.3 MiB [] 49% 1.3s167.3 MiB [] 50% 1.3s167.3 MiB [] 51% 1.3s167.3 MiB [] 52% 1.2s167.3 MiB [] 53% 1.2s167.3 MiB [] 54% 1.2s167.3 MiB [] 55% 1.1s167.3 MiB [] 56% 1.1s167.3 MiB [] 57% 1.1s167.3 MiB [] 58% 1.1s167.3 MiB [] 59% 1.0s167.3 MiB [] 60% 1.0s167.3 MiB [] 61% 0.9s167.3 MiB [] 63% 0.9s167.3 MiB [] 64% 0.9s167.3 MiB [] 65% 0.8s167.3 MiB [] 66% 0.8s167.3 MiB [] 68% 0.8s167.3 MiB [] 68% 0.7s167.3 MiB [] 69% 0.7s167.3 MiB [] 70% 0.7s167.3 MiB [] 71% 0.7s167.3 MiB [] 72% 0.7s167.3 MiB [] 73% 0.7s167.3 MiB [] 74% 0.6s167.3 MiB [] 75% 0.6s167.3 MiB [] 76% 0.6s167.3 MiB [] 77% 0.6s167.3 MiB [] 78% 0.5s167.3 MiB [] 80% 0.5s167.3 MiB [] 81% 0.4s167.3 MiB [] 83% 0.4s167.3 MiB [] 84% 0.4s167.3 MiB [] 85% 0.3s167.3 MiB [] 87% 0.3s167.3 MiB [] 88% 0.3s167.3 MiB [] 89% 0.2s167.3 MiB [] 91% 0.2s167.3 MiB [] 92% 0.2s167.3 MiB [] 93% 0.1s167.3 MiB [] 95% 0.1s167.3 MiB [] 96% 0.1s167.3 MiB [] 97% 0.0s167.3 MiB [] 98% 0.0s167.3 MiB [] 99% 0.0s167.3 MiB [] 100% 0.0s
Chrome for Testing 145.0.7632.6 (playwright chromium v1208) downloaded to /root/.cache/ms-playwright/chromium-1208
Downloading Chrome Headless Shell 145.0.7632.6 (playwright chromium-headless-shell v1208) from https://cdn.playwright.dev/chrome-for-testing-public/145.0.7632.6/linux64/chrome-headless-shell-linux64.zip
(node:7284) [DEP0169] DeprecationWarning: `url.parse()` behavior is not standardized and prone to errors that have security implications. Use the WHATWG URL API instead. CVEs are not issued for `url.parse()` vulnerabilities.
(Use `node --trace-deprecation ...` to show where the warning was created)
110.9 MiB [] 0% 0.0s110.9 MiB [] 0% 16.4s110.9 MiB [] 0% 8.7s110.9 MiB [] 0% 6.8s110.9 MiB [] 1% 3.8s110.9 MiB [] 2% 2.8s110.9 MiB [] 3% 2.4s110.9 MiB [] 4% 2.6s110.9 MiB [] 4% 2.7s110.9 MiB [] 5% 2.8s110.9 MiB [] 5% 2.7s110.9 MiB [] 6% 2.6s110.9 MiB [] 7% 2.4s110.9 MiB [] 9% 2.1s110.9 MiB [] 10% 1.9s110.9 MiB [] 11% 1.9s110.9 MiB [] 12% 1.9s110.9 MiB [] 12% 2.1s110.9 MiB [] 13% 2.0s110.9 MiB [] 14% 1.8s110.9 MiB [] 16% 1.7s110.9 MiB [] 17% 1.6s110.9 MiB [] 18% 1.6s110.9 MiB [] 20% 1.5s110.9 MiB [] 21% 1.4s110.9 MiB [] 23% 1.4s110.9 MiB [] 24% 1.4s110.9 MiB [] 25% 1.4s110.9 MiB [] 26% 1.3s110.9 MiB [] 26% 1.4s110.9 MiB [] 27% 1.4s110.9 MiB [] 28% 1.3s110.9 MiB [] 29% 1.3s110.9 MiB [] 30% 1.3s110.9 MiB [] 32% 1.3s110.9 MiB [] 33% 1.2s110.9 MiB [] 35% 1.1s110.9 MiB [] 37% 1.1s110.9 MiB [] 38% 1.0s110.9 MiB [] 40% 1.0s110.9 MiB [] 42% 1.0s110.9 MiB [] 43% 0.9s110.9 MiB [] 45% 0.9s110.9 MiB [] 46% 0.9s110.9 MiB [] 47% 0.9s110.9 MiB [] 48% 0.8s110.9 MiB [] 50% 0.8s110.9 MiB [] 52% 0.8s110.9 MiB [] 54% 0.7s110.9 MiB [] 56% 0.7s110.9 MiB [] 57% 0.7s110.9 MiB [] 58% 0.6s110.9 MiB [] 59% 0.8s110.9 MiB [] 60% 0.8s110.9 MiB [] 61% 0.7s110.9 MiB [] 63% 0.7s110.9 MiB [] 64% 0.7s110.9 MiB [] 65% 0.6s110.9 MiB [] 67% 0.6s110.9 MiB [] 68% 0.6s110.9 MiB [] 69% 0.6s110.9 MiB [] 71% 0.5s110.9 MiB [] 72% 0.5s110.9 MiB [] 73% 0.5s110.9 MiB [] 74% 0.5s110.9 MiB [] 76% 0.4s110.9 MiB [] 77% 0.4s110.9 MiB [] 78% 0.4s110.9 MiB [] 79% 0.4s110.9 MiB [] 81% 0.3s110.9 MiB [] 82% 0.3s110.9 MiB [] 84% 0.3s110.9 MiB [] 85% 0.3s110.9 MiB [] 86% 0.2s110.9 MiB [] 88% 0.2s110.9 MiB [] 89% 0.2s110.9 MiB [] 91% 0.1s110.9 MiB [] 93% 0.1s110.9 MiB [] 95% 0.1s110.9 MiB [] 96% 0.1s110.9 MiB [] 97% 0.0s110.9 MiB [] 100% 0.0s
Chrome Headless Shell 145.0.7632.6 (playwright chromium-headless-shell v1208) downloaded to /root/.cache/ms-playwright/chromium_headless_shell-1208
Downloading Firefox 146.0.1 (playwright firefox v1509) from https://cdn.playwright.dev/dbazure/download/playwright/builds/firefox/1509/firefox-ubuntu-22.04.zip
(node:7319) [DEP0169] DeprecationWarning: `url.parse()` behavior is not standardized and prone to errors that have security implications. Use the WHATWG URL API instead. CVEs are not issued for `url.parse()` vulnerabilities.
(Use `node --trace-deprecation ...` to show where the warning was created)
99.5 MiB [] 0% 0.0s99.5 MiB [] 0% 10.2s99.5 MiB [] 0% 4.6s99.5 MiB [] 1% 3.1s99.5 MiB [] 1% 3.3s99.5 MiB [] 2% 2.9s99.5 MiB [] 3% 2.8s99.5 MiB [] 4% 2.7s99.5 MiB [] 4% 2.6s99.5 MiB [] 5% 2.4s99.5 MiB [] 6% 2.3s99.5 MiB [] 7% 2.3s99.5 MiB [] 7% 2.4s99.5 MiB [] 8% 2.3s99.5 MiB [] 10% 2.0s99.5 MiB [] 12% 1.8s99.5 MiB [] 13% 1.8s99.5 MiB [] 14% 1.7s99.5 MiB [] 15% 1.6s99.5 MiB [] 17% 1.5s99.5 MiB [] 18% 1.4s99.5 MiB [] 20% 1.4s99.5 MiB [] 22% 1.3s99.5 MiB [] 23% 1.2s99.5 MiB [] 25% 1.2s99.5 MiB [] 27% 1.1s99.5 MiB [] 29% 1.0s99.5 MiB [] 30% 1.0s99.5 MiB [] 31% 1.0s99.5 MiB [] 33% 1.0s99.5 MiB [] 34% 0.9s99.5 MiB [] 36% 0.9s99.5 MiB [] 38% 0.8s99.5 MiB [] 40% 0.8s99.5 MiB [] 42% 0.8s99.5 MiB [] 43% 0.7s99.5 MiB [] 44% 0.7s99.5 MiB [] 46% 0.7s99.5 MiB [] 47% 0.7s99.5 MiB [] 48% 0.7s99.5 MiB [] 50% 0.7s99.5 MiB [] 51% 0.6s99.5 MiB [] 53% 0.6s99.5 MiB [] 54% 0.6s99.5 MiB [] 55% 0.6s99.5 MiB [] 56% 0.6s99.5 MiB [] 58% 0.5s99.5 MiB [] 59% 0.5s99.5 MiB [] 60% 0.5s99.5 MiB [] 62% 0.5s99.5 MiB [] 64% 0.5s99.5 MiB [] 66% 0.4s99.5 MiB [] 69% 0.4s99.5 MiB [] 71% 0.4s99.5 MiB [] 74% 0.3s99.5 MiB [] 76% 0.3s99.5 MiB [] 79% 0.2s99.5 MiB [] 81% 0.2s99.5 MiB [] 82% 0.2s99.5 MiB [] 85% 0.2s99.5 MiB [] 87% 0.2s99.5 MiB [] 89% 0.1s99.5 MiB [] 91% 0.1s99.5 MiB [] 93% 0.1s99.5 MiB [] 95% 0.1s99.5 MiB [] 97% 0.0s99.5 MiB [] 98% 0.0s99.5 MiB [] 100% 0.0s
Firefox 146.0.1 (playwright firefox v1509) downloaded to /root/.cache/ms-playwright/firefox-1509
Downloading WebKit 26.0 (playwright webkit v2248) from https://cdn.playwright.dev/dbazure/download/playwright/builds/webkit/2248/webkit-ubuntu-22.04.zip
(node:7354) [DEP0169] DeprecationWarning: `url.parse()` behavior is not standardized and prone to errors that have security implications. Use the WHATWG URL API instead. CVEs are not issued for `url.parse()` vulnerabilities.
(Use `node --trace-deprecation ...` to show where the warning was created)
99.4 MiB [] 0% 0.0s99.4 MiB [] 0% 7.3s99.4 MiB [] 0% 4.1s99.4 MiB [] 1% 3.5s99.4 MiB [] 2% 2.9s99.4 MiB [] 2% 2.6s99.4 MiB [] 3% 2.6s99.4 MiB [] 4% 2.5s99.4 MiB [] 5% 2.5s99.4 MiB [] 6% 2.5s99.4 MiB [] 6% 2.4s99.4 MiB [] 7% 2.5s99.4 MiB [] 7% 2.6s99.4 MiB [] 8% 2.4s99.4 MiB [] 9% 2.2s99.4 MiB [] 11% 2.1s99.4 MiB [] 12% 2.0s99.4 MiB [] 13% 2.0s99.4 MiB [] 14% 2.0s99.4 MiB [] 15% 1.9s99.4 MiB [] 16% 1.9s99.4 MiB [] 17% 1.9s99.4 MiB [] 18% 1.9s99.4 MiB [] 19% 1.9s99.4 MiB [] 20% 1.8s99.4 MiB [] 21% 1.8s99.4 MiB [] 22% 1.8s99.4 MiB [] 23% 1.8s99.4 MiB [] 24% 1.7s99.4 MiB [] 25% 1.6s99.4 MiB [] 27% 1.6s99.4 MiB [] 28% 1.5s99.4 MiB [] 28% 1.6s99.4 MiB [] 30% 1.5s99.4 MiB [] 31% 1.5s99.4 MiB [] 32% 1.4s99.4 MiB [] 32% 1.5s99.4 MiB [] 33% 1.4s99.4 MiB [] 35% 1.4s99.4 MiB [] 36% 1.3s99.4 MiB [] 37% 1.3s99.4 MiB [] 38% 1.2s99.4 MiB [] 39% 1.2s99.4 MiB [] 40% 1.2s99.4 MiB [] 41% 1.2s99.4 MiB [] 42% 1.1s99.4 MiB [] 43% 1.1s99.4 MiB [] 45% 1.1s99.4 MiB [] 47% 1.1s99.4 MiB [] 48% 1.0s99.4 MiB [] 49% 1.0s99.4 MiB [] 50% 1.0s99.4 MiB [] 51% 1.0s99.4 MiB [] 52% 1.0s99.4 MiB [] 53% 1.0s99.4 MiB [] 54% 1.0s99.4 MiB [] 54% 0.9s99.4 MiB [] 55% 0.9s99.4 MiB [] 56% 0.9s99.4 MiB [] 57% 0.9s99.4 MiB [] 58% 0.9s99.4 MiB [] 59% 0.8s99.4 MiB [] 61% 0.8s99.4 MiB [] 62% 0.8s99.4 MiB [] 63% 0.8s99.4 MiB [] 64% 0.8s99.4 MiB [] 65% 0.7s99.4 MiB [] 67% 0.7s99.4 MiB [] 68% 0.7s99.4 MiB [] 69% 0.6s99.4 MiB [] 70% 0.6s99.4 MiB [] 71% 0.6s99.4 MiB [] 72% 0.6s99.4 MiB [] 73% 0.5s99.4 MiB [] 74% 0.5s99.4 MiB [] 76% 0.5s99.4 MiB [] 77% 0.5s99.4 MiB [] 78% 0.4s99.4 MiB [] 79% 0.4s99.4 MiB [] 80% 0.4s99.4 MiB [] 81% 0.4s99.4 MiB [] 82% 0.4s99.4 MiB [] 82% 0.3s99.4 MiB [] 83% 0.3s99.4 MiB [] 85% 0.3s99.4 MiB [] 86% 0.3s99.4 MiB [] 87% 0.2s99.4 MiB [] 89% 0.2s99.4 MiB [] 90% 0.2s99.4 MiB [] 91% 0.2s99.4 MiB [] 92% 0.1s99.4 MiB [] 93% 0.1s99.4 MiB [] 95% 0.1s99.4 MiB [] 96% 0.1s99.4 MiB [] 98% 0.0s99.4 MiB [] 99% 0.0s99.4 MiB [] 100% 0.0s
WebKit 26.0 (playwright webkit v2248) downloaded to /root/.cache/ms-playwright/webkit-2248
Downloading FFmpeg (playwright ffmpeg v1011) from https://cdn.playwright.dev/dbazure/download/playwright/builds/ffmpeg/1011/ffmpeg-linux.zip
(node:7401) [DEP0169] DeprecationWarning: `url.parse()` behavior is not standardized and prone to errors that have security implications. Use the WHATWG URL API instead. CVEs are not issued for `url.parse()` vulnerabilities.
(Use `node --trace-deprecation ...` to show where the warning was created)
2.3 MiB [] 0% 0.0s2.3 MiB [] 4% 0.5s2.3 MiB [] 31% 0.1s2.3 MiB [] 57% 0.0s2.3 MiB [] 73% 0.0s2.3 MiB [] 100% 0.0s
FFmpeg (playwright ffmpeg v1011) downloaded to /root/.cache/ms-playwright/ffmpeg-1011
Playwright Host validation warning:
╔══════════════════════════════════════════════════════╗
║ Host system is missing dependencies to run browsers. ║
║ Please install them with the following command:      ║
║                                                      ║
║     playwright install-deps                          ║
║                                                      ║
║ Alternatively, use apt:                              ║
║     apt-get install libxcomposite1\                  ║
║         libgtk-3-0\                                  ║
║         libatk1.0-0                                  ║
║                                                      ║
║ <3 Playwright Team                                   ║
╚══════════════════════════════════════════════════════╝
    at validateDependenciesLinux (/usr/local/lib/python3.12/dist-packages/playwright/driver/package/lib/server/registry/dependencies.js:269:9)
    at process.processTicksAndRejections (node:internal/process/task_queues:103:5)
    at async Registry._validateHostRequirements (/usr/local/lib/python3.12/dist-packages/playwright/driver/package/lib/server/registry/index.js:991:14)
    at async Registry._validateHostRequirementsForExecutableIfNeeded (/usr/local/lib/python3.12/dist-packages/playwright/driver/package/lib/server/registry/index.js:1113:7)
    at async Registry.validateHostRequirementsForExecutablesIfNeeded (/usr/local/lib/python3.12/dist-packages/playwright/driver/package/lib/server/registry/index.js:1102:7)
    at async i.<anonymous> (/usr/local/lib/python3.12/dist-packages/playwright/driver/package/lib/cli/program.js:174:7)

In [ ]:
from youtube_comment_downloader import YoutubeCommentDownloader
import pandas as pd

downloader = YoutubeCommentDownloader()

url = "https://www.youtube.com/watch?v=J5HzbEc_atI"

comments = []
for i, comment in enumerate(downloader.get_comments_from_url(url)):
    comments.append({
        "username": comment['author'],
        "comment": comment['text'],
        "likes": comment['votes'],
        "time": comment['time']
    })
    if i >= 1000:
        break

df = pd.DataFrame(comments)
df.to_csv("youtube_comments.csv", index=False)

df.head()

,username,comment,likes,time
0,@tapmeatam,dagdigdug banget denger dr. Tirta cerita soal ...,0,3 hours ago
1,@uhuyyyyy111,"48:00 sampe selesai ngeri bgt cerita"" nya",0,1 day ago
2,@hahahihi555,Pokémon bang radit tampil lagi,0,1 day ago
3,@dwifajaryuliastutik8385,"Klo aku periksa milih dr Gia, klo (dosen) bela...",0,1 day ago
4,@DianWidiantara-rn7eg,pria mc itu lagi,0,2 days ago

In [ ]:
from google.colab import sheets
sheet = sheets.InteractiveSheet(df=df)

https://docs.google.com/spreadsheets/d/1g65GoefhGtQZTYcIiNe2sHIPK1OothRdTzpw5ikEiio/edit#gid=0

In [ ]:
from google_play_scraper import reviews, Sort
import pandas as pd

result, _ = reviews(
    'com.mobilechess.gp',
    lang='id',
    country='id',
    sort=Sort.NEWEST,
    count=1000
)

data = []
for r in result:
    data.append({
        "username": r['userName'],
        "rating": r['score'],
        "review": r['content'],
        "date": r['at']
    })

df = pd.DataFrame(data)
df.to_csv("playstore_reviews.csv", index=False)

df.head()

,username,rating,review,date
0,Harian Syah,5,sangat menghibur 🥰🥰,2026-03-30 02:36:24
1,Doni Ramdhani,5,niceeeeee,2026-03-30 02:22:12
2,Ridho Wandi,5,game yang seruuuu,2026-03-30 02:18:30
3,Asyifa Amin,5,Game seru tolong tingkatkan hadiah gold buat u...,2026-03-30 01:38:15
4,Riki Perdiansah,5,ini game nya seru,2026-03-30 01:34:43

In [ ]:
from google.colab import sheets
sheet = sheets.InteractiveSheet(df=df)

https://docs.google.com/spreadsheets/d/1D8AX6TjMRVQsdohJEL3NUCxQkZ7hBKqaQlSLL8cPVYw/edit#gid=0